### ISSUE TITLE
CDK Error installing 'Part B: Intelligent Claims Review'

### ISSUE THREAD

**Issue by manconor** [aws-solutions-library-samples/guidance-for-multimodal-data-processing-using-amazon-bedrock-data-automation#32]
I am installing the latest clone of 'Part B: Intelligent Claims Review'. I am getting a endpoint error when deploying with CDK. 

----------------------------------------------------------------

$ cdk deploy claims-review

claims-review: creating CloudFormation changeset...
9:45:52 AM | CREATE_FAILED        | AWS::CloudFormation::CustomResource         | bdaclaimsreviewblu...omresourceC5F3E4CD
Received response status [FAILED] from custom resource. Message returned: Error: Invalid endpoint:

Logs: /aws/lambda/claims-review-bdablueprintcreationB4DCB454-20t696aLacWd

at invokeUserFunction (/var/task/framework.js:2:6)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async onEvent (/var/task/framework.js:1:369)
at async Runtime.handler (/var/task/cfn-response.js:1:1837) (RequestId: 629675fc-8ab8-4832-816d-9c8885f21c22)

----------------------------------------------------------------

**Comment by rajavaid77** [comment]
fixed

**Comment by rajavaid77** [comment]
fixed https://github.com/aws-solutions-library-samples/guidance-for-multimodal-data-processing-using-amazon-bedrock-data-automation/pull/35
